#!/bin/bash

if [[ $1 = 'production' ]]; then
  docker/rails assets:precompile
  docker-compose exec -e RAILS_SERVE_STATIC_FILES=1 app \
    bin/rails server -b 0.0.0.0 -e production
else
  docker/rails server -b 0.0.0.0
fi
