#!/usr/bin/env bash

set -e

bundle install

database_config=config/database.yml
if [ ! -f $database_config ]
then
    cp config/database.yml.example $database_config
fi

bundle exec rake db:schema:load db:test:load
