#!/bin/bash

if [[ $1 = 'staging' ]]; then
  docker-compose exec app \
    rm -rf tmp/cache
  docker-compose exec -e RAILS_ENV=staging app \
    bin/rails assets:precompile
  docker-compose exec -e RAILS_SERVE_STATIC_FILES=1 app \
    bin/rails server -b 0.0.0.0 -e staging
else
  dc/rails server -b 0.0.0.0
fi
